### ISSUE TITLE
Update ILSpy link?

### ISSUE THREAD

**Issue by ww9** [spdskatr/RWModdingResources#2]
Hi. First of all, thank you for the page! Very useful.

I wonder if ILSpy link should be updated. It currently links to https://github.com/Zhentar/ILSpy/releases which was last updated 10 Jul 2017.

Would this be better? https://github.com/icsharpcode/ILSpy

Thanks in advance. 👍🏻

**Comment by sTiKyt** [comment]
@ww9 did you test it? Does it work?

**Comment by ww9** [comment]
@sTiKyt I didn't sorry. I'm taking a break from Rimworld modding.

But I just noticed that https://github.com/Zhentar/ILSpy has a text that directs users to use  https://github.com/icsharpcode/ILSpy instead.

Good luck @sTiKyt ❤
